name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        
    - name: Generate API documentation
      run: |
        sphinx-apidoc -f -o docs/ windtunnel
        
    - name: Build HTML documentation
      run: |
        sphinx-build -b html docs docs/_build
        
    - name: Deploy to GitHub Pages
      if: success()
      run: |
        pip install ghp-import
        ghp-import -n -p -f docs/_build
        